---
title: Weather Dashboard
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: '2018-12-06'
steps:
- title: Introduction
  completion: engaged
- title: Exploring Weather Data
- title: Creating a Weather Dashboard
  completion: internal
- title: Creating a Function
